#!/bin/bash

### TODO on each build: update mrenclave in session

docker-compose down > /dev/null
docker network create scone-net > /dev/null
echo "Starting CAS & LAS:"
docker-compose up -d
sleep 5

MY_SCONE_APP=tee-python-hello-world
echo "Starting $MY_SCONE_APP"
docker run --rm \
        --name=$MY_SCONE_APP \
        -e SCONE_VERSION=1 \
        -e SCONE_CAS_ADDR="cas" \
        -e SCONE_LAS_ADDR="las" \
        -e SCONE_CONFIG_ID="1/service" \
        --network=scone-net \
        --device=/dev/isgx \
        $MY_SCONE_APP

docker-compose down
docker network rm scone-net
