#!/bin/sh
cd $(dirname $0)

IEXEC_OUT=/tmp/iexec_out

rm -rf $IEXEC_OUT
mkdir -p $IEXEC_OUT


docker run --rm \
        -e IEXEC_OUT=/iexec_out \
        -e IEXEC_IN=/iexec_in \
        -e IEXEC_DATASET_FILENAME=Lorem_ipsum.txt \
        -e IEXEC_INPUT_FILES_NUMBER='2' \
        -e IEXEC_INPUT_FILE_NAME_1='input-file1.txt' \
        -e IEXEC_INPUT_FILE_NAME_2='input-file2.txt' \
        -v $IEXEC_OUT:/iexec_out \
        -v $(pwd)/asset:/iexec_in \
        python-hello-world $@

echo
find $IEXEC_OUT
