#!/bin/sh
cd $(dirname $0)

rm -rf /tmp/iexec_out
mkdir -p /tmp/iexec_out

sudo docker run --rm -e IEXEC_OUT=/iexec_out -v /tmp/iexec_out:/iexec_out python-hello-world:4.0.0 $@

echo
find /tmp/iexec_out/
