FROM python:3.7-alpine

RUN apk --no-cache add --virtual .builddeps gcc musl-dev
RUN pip install eth-abi pysha3
RUN apk del .builddeps
RUN rm -rf /root/.cache

COPY src/priceFeed.py /app/priceFeed.py

ENTRYPOINT [ "python3", "/app/priceFeed.py" ]
